language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install inflect==0.2.4"
  - "make install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "make test"
  - "python manage.py makemessages -l eo"
after_success:
  coveralls
